# Generated by Django 4.0.1 on 2022-02-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('passanger_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Flight_details',
            fields=[
                ('trip_id', models.IntegerField(primary_key=True, serialize=False)),
                ('flight_no', models.IntegerField()),
                ('flight_name', models.CharField(max_length=20)),
                ('from_to', models.CharField(max_length=20)),
                ('to', models.CharField(max_length=20)),
            ],
        ),
    ]
