# Generated by Django 4.0.1 on 2022-03-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('passanger_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_id', models.IntegerField()),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('g', models.CharField(max_length=1)),
                ('code', models.IntegerField()),
                ('pn', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('seat', models.CharField(max_length=1)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight_details',
            fields=[
                ('trip_id', models.IntegerField(primary_key=True, serialize=False)),
                ('flight_no', models.IntegerField()),
                ('flight_name', models.CharField(max_length=20)),
                ('from_to', models.CharField(max_length=20)),
                ('to', models.CharField(max_length=20)),
                ('from_time', models.DateTimeField()),
                ('to_time', models.DateTimeField()),
                ('cost_e', models.IntegerField()),
                ('cost_b', models.IntegerField()),
            ],
        ),
    ]
