# Generated by Django 4.0.1 on 2022-01-27 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.IntegerField()),
                ('flight_name', models.CharField(max_length=20)),
                ('travel_id', models.IntegerField()),
                ('from_to', models.CharField(max_length=20)),
                ('to', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('trip_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.flight_details')),
            ],
        ),
    ]
